# Generated by Django 4.2.15 on 2025-09-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medical_records", "0002_reportcorrectionrequest_reportcorrectionversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcorrectionrequest",
            name="medical_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correction_requests",
                to="medical_records.medicalrecord",
            ),
        ),
    ]
