# Generated by Django 4.2.15 on 2025-09-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medical_records", "0003_alter_reportcorrectionrequest_medical_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                ("original_text", models.TextField()),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Sensitivity"),
                            ("medium", "Medium Sensitivity"),
                            ("high", "High Sensitivity"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_framework",
                    models.CharField(
                        choices=[
                            ("HIPAA", "HIPAA (US Healthcare)"),
                            ("GDPR", "GDPR (EU Data Protection)"),
                            ("CUSTOM", "Custom Rules"),
                        ],
                        default="HIPAA",
                        max_length=10,
                    ),
                ),
                (
                    "anonymization_strategy",
                    models.CharField(default="REPLACEMENT", max_length=20),
                ),
                ("preserve_structure", models.BooleanField(default=True)),
                ("use_contextual_replacement", models.BooleanField(default=True)),
                ("anonymized_text", models.TextField(blank=True)),
                ("detections_json", models.JSONField(default=dict)),
                ("summary_json", models.JSONField(default=dict)),
                ("insights_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("risk_level", models.CharField(blank=True, max_length=10)),
                ("compliance_score", models.FloatField(blank=True, null=True)),
                ("detections_count", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymization_requests",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anonymization_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnonymizationConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("config_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anonymization_configurations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnonymizationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("analyze", "Text Analysis"),
                            ("anonymize", "Text Anonymization"),
                            ("export", "Export Anonymized Data"),
                            ("view", "View Anonymized Data"),
                            ("config_change", "Configuration Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details_json", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "anonymization_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="medical_records.anonymizationrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anonymization_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="anonymizationrequest",
            index=models.Index(
                fields=["request_id"], name="anonymizati_request_ee6e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymizationrequest",
            index=models.Index(fields=["status"], name="anonymizati_status_81a21e_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymizationrequest",
            index=models.Index(
                fields=["compliance_framework"], name="anonymizati_complia_6e2874_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymizationrequest",
            index=models.Index(
                fields=["created_at"], name="anonymizati_created_7fbd03_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="anonymizationconfiguration",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="anonymizationauditlog",
            index=models.Index(fields=["action"], name="anonymizati_action_fde110_idx"),
        ),
        migrations.AddIndex(
            model_name="anonymizationauditlog",
            index=models.Index(
                fields=["timestamp"], name="anonymizati_timesta_9392f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymizationauditlog",
            index=models.Index(fields=["user"], name="anonymizati_user_id_e3fb8e_idx"),
        ),
    ]
